- name: memory testing
  hosts: all
  gather_facts: false
  vars:
    filepath: "/root/1gb/test.file"

  tasks:
  - name: Read the file
    ansible.builtin.command:
      cmd: "cat {{ filepath }}"
    register: cmd_output

  - name: Replace stuff in the output
    ansible.builtin.command:
      debug: "{{ cmd_output | replace(' ','_') }}"

  - name: Sleep to check memory consumption
    ansible.builtin.pause:
      minutes: 10
